import os
import requests
from dotenv import load_dotenv

load_dotenv()

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")

HEADERS = {
    "apikey": SUPABASE_KEY,
    "Authorization": f"Bearer {SUPABASE_KEY}"
}

def init_db():
    print("Checking Database via REST API...")
    
    try:
        # Try to fetch 1 row
        url = f"{SUPABASE_URL}/rest/v1/energy_readings?limit=1"
        response = requests.get(url, headers=HEADERS)
        
        if response.status_code == 200:
            print("✅ Table 'energy_readings' exists and is accessible.")
        elif response.status_code == 404:
             # Supabase returns 404 if table doesn't exist? No, 404 if route not found. 
             # It returns 420 or error message if table missing usually.
             print(f"⚠️ Response 404. Table might not exist or URL is wrong: {response.text}")
        else:
             print(f"⚠️ Could not access table. Status: {response.status_code}")
             print(f"Body: {response.text}")
             
    except Exception as e:
        print(f"❌ Connection Error: {e}")

    print("\nIf the table does not exist, run this SQL in your Supabase Dashboard:")
    print("-" * 50)
    print("""
    CREATE TABLE IF NOT EXISTS energy_readings (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
        device_id TEXT NOT NULL,
        channel INTEGER NOT NULL,
        power_w REAL,
        voltage REAL,
        energy_total_wh REAL
    );
    """)
    print("-" * 50)

if __name__ == "__main__":
    init_db()
