-- Phase 1: durable telemetry collection lineage.
--
-- This migration is deliberately additive. Existing energy readings retain their
-- legacy columns and values; lineage fields remain NULL for rows written before
-- the collector starts sending the versioned payload.

begin;

-- Keep a fresh local Supabase project usable while leaving an existing production
-- table (including its current primary key) unchanged.
create table if not exists public.energy_readings (
    id bigint generated by default as identity primary key,
    device_id text not null,
    channel integer not null,
    power_w double precision,
    voltage double precision,
    energy_total_wh double precision,
    created_at timestamptz not null default now()
);

create table if not exists public.telemetry_polls (
    poll_id uuid primary key,
    site_id text not null,
    device_id text not null,
    collector_id text not null,
    source text not null default 'shelly_cloud',
    sampling_policy_version integer not null default 1,
    scheduled_at timestamptz,
    request_started_at timestamptz not null,
    received_at timestamptz,
    completed_at timestamptz not null,
    outcome text not null,
    error_code text,
    error_message text,
    latency_ms integer,
    http_status integer,
    poll_sequence bigint,
    payload_hash text,
    raw_payload jsonb,
    created_at timestamptz not null default now(),
    constraint telemetry_polls_source_nonempty_check
        check (btrim(source) <> ''),
    constraint telemetry_polls_site_nonempty_check
        check (btrim(site_id) <> ''),
    constraint telemetry_polls_collector_nonempty_check
        check (btrim(collector_id) <> ''),
    constraint telemetry_polls_sampling_policy_version_check
        check (sampling_policy_version >= 1),
    constraint telemetry_polls_outcome_check
        check (outcome in ('success', 'source_error', 'persistence_error', 'unexpected_error')),
    constraint telemetry_polls_latency_check
        check (latency_ms is null or latency_ms >= 0),
    constraint telemetry_polls_http_status_check
        check (http_status is null or http_status between 100 and 599),
    constraint telemetry_polls_sequence_check
        check (poll_sequence is null or poll_sequence >= 0),
    constraint telemetry_polls_received_order_check
        check (received_at is null or received_at >= request_started_at),
    constraint telemetry_polls_completed_order_check
        check (completed_at >= request_started_at)
);

alter table public.energy_readings
    add column if not exists poll_id uuid,
    add column if not exists site_id text,
    add column if not exists observed_at timestamptz,
    add column if not exists received_at timestamptz,
    add column if not exists collector_id text,
    add column if not exists sample_reason text,
    add column if not exists quality_flags text[],
    add column if not exists schema_version integer;

-- Invalid or absent source measurements are represented as NULL plus an
-- explanatory quality flag. Older deployments declared these columns NOT NULL,
-- so relax them without rewriting any existing values.
alter table public.energy_readings
    alter column power_w drop not null,
    alter column voltage drop not null,
    alter column energy_total_wh drop not null;

comment on table public.telemetry_polls is
    'One immutable collection attempt. Raw readings reference it through energy_readings.poll_id.';
comment on column public.energy_readings.observed_at is
    'Timestamp reported by the source when available; NULL for legacy rows.';
comment on column public.energy_readings.received_at is
    'Timestamp at which the collector received the source response; NULL for legacy rows.';
comment on column public.energy_readings.created_at is
    'Legacy persistence timestamp retained for dashboard and API compatibility.';
comment on column public.energy_readings.sample_reason is
    'Why this sparse sample was retained (for example active, turned_off, or heartbeat).';
comment on column public.energy_readings.quality_flags is
    'Collector-assigned data-quality flags. NULL means unknown legacy quality, not an empty flag set.';
comment on column public.energy_readings.schema_version is
    'Collector payload contract version. NULL identifies legacy rows.';
comment on column public.energy_readings.site_id is
    'Stable installation/site scope. NULL is retained only for legacy rows.';

do $migration$
begin
    if not exists (
        select 1
        from pg_constraint
        where conrelid = 'public.energy_readings'::regclass
          and conname = 'energy_readings_poll_id_fkey'
    ) then
        alter table public.energy_readings
            add constraint energy_readings_poll_id_fkey
            foreign key (poll_id)
            references public.telemetry_polls (poll_id)
            on delete set null
            not valid;
    end if;

    if not exists (
        select 1
        from pg_constraint
        where conrelid = 'public.energy_readings'::regclass
          and conname = 'energy_readings_site_nonempty_check'
    ) then
        alter table public.energy_readings
            add constraint energy_readings_site_nonempty_check
            check (site_id is null or btrim(site_id) <> '')
            not valid;
    end if;

    if not exists (
        select 1
        from pg_constraint
        where conrelid = 'public.energy_readings'::regclass
          and conname = 'energy_readings_v1_site_required_check'
    ) then
        alter table public.energy_readings
            add constraint energy_readings_v1_site_required_check
            check (schema_version is null or site_id is not null)
            not valid;
    end if;

    if not exists (
        select 1
        from pg_constraint
        where conrelid = 'public.energy_readings'::regclass
          and conname = 'energy_readings_schema_version_check'
    ) then
        alter table public.energy_readings
            add constraint energy_readings_schema_version_check
            check (schema_version is null or schema_version >= 1)
            not valid;
    end if;

    if not exists (
        select 1
        from pg_constraint
        where conrelid = 'public.energy_readings'::regclass
          and conname = 'energy_readings_sample_reason_check'
    ) then
        alter table public.energy_readings
            add constraint energy_readings_sample_reason_check
            check (
                sample_reason is null
                or sample_reason in (
                    'first',
                    'active',
                    'turned_off',
                    'heartbeat',
                    'periodic',
                    'manual',
                    'recovered'
                )
            )
            not valid;
    end if;

    if not exists (
        select 1
        from pg_constraint
        where conrelid = 'public.energy_readings'::regclass
          and conname = 'energy_readings_collector_nonempty_check'
    ) then
        alter table public.energy_readings
            add constraint energy_readings_collector_nonempty_check
            check (collector_id is null or btrim(collector_id) <> '')
            not valid;
    end if;

    if not exists (
        select 1
        from pg_constraint
        where conrelid = 'public.energy_readings'::regclass
          and conname = 'energy_readings_quality_flags_check'
    ) then
        alter table public.energy_readings
            add constraint energy_readings_quality_flags_check
            check (
                quality_flags is null
                or (
                    array_position(quality_flags, null) is null
                    and array_position(quality_flags, '') is null
                )
            )
            not valid;
    end if;
end
$migration$;

-- The new columns are NULL on all legacy rows, so validation does not rewrite or
-- reject the existing telemetry. It does make every new row obey the contract.
alter table public.energy_readings validate constraint energy_readings_poll_id_fkey;
alter table public.energy_readings validate constraint energy_readings_site_nonempty_check;
alter table public.energy_readings validate constraint energy_readings_v1_site_required_check;
alter table public.energy_readings validate constraint energy_readings_schema_version_check;
alter table public.energy_readings validate constraint energy_readings_sample_reason_check;
alter table public.energy_readings validate constraint energy_readings_collector_nonempty_check;
alter table public.energy_readings validate constraint energy_readings_quality_flags_check;

-- A real UNIQUE constraint (rather than a partial index) is required for
-- PostgREST's on_conflict=poll_id,device_id,channel retry contract. PostgreSQL's
-- default NULL-distinct semantics allow duplicate legacy rows whose poll_id is
-- NULL while making every versioned poll/channel insert idempotent.
drop index if exists public.energy_readings_poll_device_channel_uidx;
do $migration$
begin
    if not exists (
        select 1
        from pg_constraint
        where conrelid = 'public.energy_readings'::regclass
          and conname = 'energy_readings_poll_device_channel_key'
    ) then
        alter table public.energy_readings
            add constraint energy_readings_poll_device_channel_key
            unique (poll_id, device_id, channel);
    end if;
end
$migration$;

create index if not exists energy_readings_channel_created_at_idx
    on public.energy_readings (channel, created_at desc);

create index if not exists energy_readings_device_channel_created_at_idx
    on public.energy_readings (device_id, channel, created_at desc);

create index if not exists energy_readings_site_device_channel_created_at_idx
    on public.energy_readings (site_id, device_id, channel, created_at desc);

-- Scoped dashboard RPCs scan both channels inside a bounded time range. Keep
-- created_at before channel so PostgreSQL can restrict the range without
-- scanning the meter's entire history.
create index if not exists energy_readings_site_device_created_at_channel_idx
    on public.energy_readings (site_id, device_id, created_at desc, channel);

create index if not exists energy_readings_poll_id_idx
    on public.energy_readings (poll_id)
    where poll_id is not null;

create index if not exists energy_readings_device_observed_at_idx
    on public.energy_readings (device_id, observed_at desc)
    where observed_at is not null;

create index if not exists telemetry_polls_device_started_at_idx
    on public.telemetry_polls (device_id, request_started_at desc);

create index if not exists telemetry_polls_site_device_started_at_idx
    on public.telemetry_polls (site_id, device_id, request_started_at desc);

create index if not exists telemetry_polls_collector_started_at_idx
    on public.telemetry_polls (collector_id, request_started_at desc);

create index if not exists telemetry_polls_outcome_started_at_idx
    on public.telemetry_polls (outcome, request_started_at desc);

create index if not exists telemetry_polls_collector_sequence_idx
    on public.telemetry_polls (collector_id, poll_sequence)
    where poll_sequence is not null;

-- Browser clients retain read-only access to the existing telemetry table.
-- Mutation requires the server-side service_role key, even if an older project
-- happened to grant broader table privileges before RLS was enabled.
alter table public.energy_readings enable row level security;
alter table public.telemetry_polls enable row level security;

revoke all privileges on table public.energy_readings from public, anon, authenticated;
revoke all privileges on table public.telemetry_polls from public, anon, authenticated;

grant select on table public.energy_readings to anon, authenticated;
grant all privileges on table public.energy_readings to service_role;
grant all privileges on table public.telemetry_polls to service_role;

drop policy if exists energy_readings_dashboard_read on public.energy_readings;
create policy energy_readings_dashboard_read
    on public.energy_readings
    for select
    to anon, authenticated
    using (true);

drop policy if exists energy_readings_service_role_all on public.energy_readings;
create policy energy_readings_service_role_all
    on public.energy_readings
    for all
    to service_role
    using (true)
    with check (true);

drop policy if exists telemetry_polls_service_role_all on public.telemetry_polls;
create policy telemetry_polls_service_role_all
    on public.telemetry_polls
    for all
    to service_role
    using (true)
    with check (true);

-- If this migration created the legacy table in a fresh project, allow the
-- service role to consume its identity sequence. Existing UUID/custom keys are
-- left untouched because pg_get_serial_sequence returns NULL for them.
do $migration$
declare
    sequence_name text;
begin
    sequence_name := pg_get_serial_sequence('public.energy_readings', 'id');
    if sequence_name is not null then
        execute format('grant usage, select on sequence %s to service_role', sequence_name);
    end if;
end
$migration$;

-- Commit the poll result and all of its channel readings as one transaction.
-- PostgREST invokes this function in a single database transaction, so any
-- validation or insert failure rolls back both the parent and its children.
-- The deterministic poll UUID makes a lost-response retry safe: a committed
-- success cannot be downgraded by a later failure, while a previously recorded
-- failure can be atomically promoted when the retry obtains valid readings.
drop function if exists public.ingest_telemetry_poll(jsonb, jsonb);
create function public.ingest_telemetry_poll(
    p_poll jsonb,
    p_readings jsonb
)
returns jsonb
language plpgsql
volatile
security invoker
set search_path = ''
as $function$
declare
    v_key text;
    v_reading jsonb;
    v_flag jsonb;
    v_poll_id uuid;
    v_site_id text;
    v_device_id text;
    v_collector_id text;
    v_source text;
    v_sampling_policy_version integer;
    v_scheduled_at timestamptz;
    v_request_started_at timestamptz;
    v_received_at timestamptz;
    v_completed_at timestamptz;
    v_outcome text;
    v_error_code text;
    v_error_message text;
    v_latency_ms integer;
    v_http_status integer;
    v_poll_sequence bigint;
    v_payload_hash text;
    v_raw_payload jsonb;
    v_channel integer;
    v_power_w double precision;
    v_voltage double precision;
    v_energy_total_wh double precision;
    v_created_at timestamptz;
    v_observed_at timestamptz;
    v_reading_received_at timestamptz;
    v_sample_reason text;
    v_quality_flags text[];
    v_schema_version integer;
    v_channels integer[] := array[]::integer[];
    v_reading_count integer;
    v_existing_reading_count integer;
    v_final_reading_count integer;
    v_existing public.telemetry_polls%rowtype;
    v_had_existing boolean := false;
    v_status text;
begin
    if pg_catalog.jsonb_typeof(p_poll) is distinct from 'object' then
        raise exception 'p_poll must be a JSON object' using errcode = '22023';
    end if;
    if pg_catalog.jsonb_typeof(p_readings) is distinct from 'array' then
        raise exception 'p_readings must be a JSON array' using errcode = '22023';
    end if;

    if exists (
        select 1
        from pg_catalog.jsonb_object_keys(p_poll) as supplied(key)
        where not (supplied.key = any (array[
            'poll_id', 'site_id', 'device_id', 'collector_id', 'source',
            'sampling_policy_version', 'scheduled_at', 'request_started_at',
            'received_at', 'completed_at', 'outcome', 'error_code',
            'error_message', 'latency_ms', 'http_status', 'poll_sequence',
            'payload_hash', 'raw_payload'
        ]::text[]))
    ) then
        raise exception 'p_poll contains unsupported fields' using errcode = '22023';
    end if;

    foreach v_key in array array[
        'poll_id', 'site_id', 'device_id', 'collector_id', 'source',
        'scheduled_at', 'request_started_at', 'completed_at', 'outcome'
    ]::text[] loop
        if pg_catalog.jsonb_typeof(p_poll -> v_key) is distinct from 'string'
           or pg_catalog.btrim(p_poll ->> v_key) = '' then
            raise exception 'p_poll.% must be a non-empty string', v_key
                using errcode = '22023';
        end if;
    end loop;

    if pg_catalog.jsonb_typeof(p_poll -> 'sampling_policy_version') is distinct from 'number' then
        raise exception 'p_poll.sampling_policy_version must be an integer'
            using errcode = '22023';
    end if;

    foreach v_key in array array['received_at', 'error_code', 'error_message', 'payload_hash']::text[] loop
        if p_poll ? v_key
           and pg_catalog.jsonb_typeof(p_poll -> v_key) not in ('string', 'null') then
            raise exception 'p_poll.% must be a string or null', v_key
                using errcode = '22023';
        end if;
    end loop;

    foreach v_key in array array['latency_ms', 'http_status', 'poll_sequence']::text[] loop
        if p_poll ? v_key
           and pg_catalog.jsonb_typeof(p_poll -> v_key) not in ('number', 'null') then
            raise exception 'p_poll.% must be a number or null', v_key
                using errcode = '22023';
        end if;
    end loop;

    begin
        v_poll_id := (p_poll ->> 'poll_id')::uuid;
        v_sampling_policy_version := (p_poll ->> 'sampling_policy_version')::integer;
        v_scheduled_at := (p_poll ->> 'scheduled_at')::timestamptz;
        v_request_started_at := (p_poll ->> 'request_started_at')::timestamptz;
        v_completed_at := (p_poll ->> 'completed_at')::timestamptz;
        v_received_at := case
            when pg_catalog.jsonb_typeof(p_poll -> 'received_at') = 'string'
                then (p_poll ->> 'received_at')::timestamptz
            else null
        end;
        v_latency_ms := case
            when pg_catalog.jsonb_typeof(p_poll -> 'latency_ms') = 'number'
                then (p_poll ->> 'latency_ms')::integer
            else null
        end;
        v_http_status := case
            when pg_catalog.jsonb_typeof(p_poll -> 'http_status') = 'number'
                then (p_poll ->> 'http_status')::integer
            else null
        end;
        v_poll_sequence := case
            when pg_catalog.jsonb_typeof(p_poll -> 'poll_sequence') = 'number'
                then (p_poll ->> 'poll_sequence')::bigint
            else null
        end;
    exception
        when invalid_text_representation or numeric_value_out_of_range or datetime_field_overflow then
            raise exception 'p_poll contains an invalid UUID, integer, or timestamp'
                using errcode = '22023';
    end;

    v_site_id := pg_catalog.btrim(p_poll ->> 'site_id');
    v_device_id := pg_catalog.btrim(p_poll ->> 'device_id');
    v_collector_id := pg_catalog.btrim(p_poll ->> 'collector_id');
    v_source := pg_catalog.btrim(p_poll ->> 'source');
    v_outcome := p_poll ->> 'outcome';
    v_error_code := case
        when pg_catalog.jsonb_typeof(p_poll -> 'error_code') = 'string'
            then p_poll ->> 'error_code'
        else null
    end;
    v_error_message := case
        when pg_catalog.jsonb_typeof(p_poll -> 'error_message') = 'string'
            then p_poll ->> 'error_message'
        else null
    end;
    v_payload_hash := case
        when pg_catalog.jsonb_typeof(p_poll -> 'payload_hash') = 'string'
            then p_poll ->> 'payload_hash'
        else null
    end;
    v_raw_payload := nullif(p_poll -> 'raw_payload', 'null'::jsonb);
    v_reading_count := pg_catalog.jsonb_array_length(p_readings);

    if (p_poll ->> 'scheduled_at') !~ '(Z|[+-][0-9]{2}:[0-9]{2})$'
       or (p_poll ->> 'request_started_at') !~ '(Z|[+-][0-9]{2}:[0-9]{2})$'
       or (p_poll ->> 'completed_at') !~ '(Z|[+-][0-9]{2}:[0-9]{2})$'
       or (
           pg_catalog.jsonb_typeof(p_poll -> 'received_at') = 'string'
           and (p_poll ->> 'received_at') !~ '(Z|[+-][0-9]{2}:[0-9]{2})$'
       ) then
        raise exception 'p_poll timestamps must include a UTC offset'
            using errcode = '22023';
    end if;
    if v_source <> 'shelly_cloud' then
        raise exception 'p_poll.source is unsupported' using errcode = '22023';
    end if;
    if v_sampling_policy_version < 1 then
        raise exception 'p_poll.sampling_policy_version must be positive'
            using errcode = '22023';
    end if;
    if v_outcome not in ('success', 'source_error', 'persistence_error', 'unexpected_error') then
        raise exception 'p_poll.outcome is unsupported' using errcode = '22023';
    end if;
    if v_completed_at < v_request_started_at
       or (v_received_at is not null and (
           v_received_at < v_request_started_at or v_received_at > v_completed_at
       )) then
        raise exception 'p_poll timestamps are out of order' using errcode = '22023';
    end if;
    if v_latency_ms is not null and v_latency_ms < 0 then
        raise exception 'p_poll.latency_ms must not be negative' using errcode = '22023';
    end if;
    if v_http_status is not null and (v_http_status < 100 or v_http_status > 599) then
        raise exception 'p_poll.http_status must be between 100 and 599'
            using errcode = '22023';
    end if;
    if v_poll_sequence is not null and v_poll_sequence < 0 then
        raise exception 'p_poll.poll_sequence must not be negative' using errcode = '22023';
    end if;
    if v_payload_hash is not null and v_payload_hash !~ '^[0-9a-f]{64}$' then
        raise exception 'p_poll.payload_hash must be a lowercase SHA-256 digest'
            using errcode = '22023';
    end if;
    if v_outcome = 'success' then
        if v_received_at is null or v_reading_count < 1 or v_reading_count > 32 then
            raise exception 'successful polls require received_at and 1 to 32 readings'
                using errcode = '22023';
        end if;
        if v_error_code is not null or v_error_message is not null then
            raise exception 'successful polls must not include error fields'
                using errcode = '22023';
        end if;
    elsif v_reading_count <> 0 then
        raise exception 'unsuccessful polls must not include readings' using errcode = '22023';
    end if;

    -- Validate every child before taking a lock or changing either table.
    for v_reading in
        select item.value
        from pg_catalog.jsonb_array_elements(p_readings) as item(value)
    loop
        if pg_catalog.jsonb_typeof(v_reading) is distinct from 'object' then
            raise exception 'every p_readings item must be an object' using errcode = '22023';
        end if;
        if exists (
            select 1
            from pg_catalog.jsonb_object_keys(v_reading) as supplied(key)
            where not (supplied.key = any (array[
                'poll_id', 'site_id', 'device_id', 'channel', 'power_w',
                'voltage', 'energy_total_wh', 'created_at', 'observed_at',
                'received_at', 'collector_id', 'sample_reason',
                'quality_flags', 'schema_version'
            ]::text[]))
        ) then
            raise exception 'a p_readings item contains unsupported fields'
                using errcode = '22023';
        end if;

        foreach v_key in array array[
            'poll_id', 'site_id', 'device_id', 'created_at', 'observed_at',
            'received_at', 'collector_id', 'sample_reason'
        ]::text[] loop
            if pg_catalog.jsonb_typeof(v_reading -> v_key) is distinct from 'string'
               or pg_catalog.btrim(v_reading ->> v_key) = '' then
                raise exception 'reading.% must be a non-empty string', v_key
                    using errcode = '22023';
            end if;
        end loop;
        foreach v_key in array array['channel', 'schema_version']::text[] loop
            if pg_catalog.jsonb_typeof(v_reading -> v_key) is distinct from 'number' then
                raise exception 'reading.% must be an integer', v_key
                    using errcode = '22023';
            end if;
        end loop;
        foreach v_key in array array['power_w', 'voltage', 'energy_total_wh']::text[] loop
            if not (v_reading ? v_key)
               or pg_catalog.jsonb_typeof(v_reading -> v_key) not in ('number', 'null') then
                raise exception 'reading.% must be a number or null', v_key
                    using errcode = '22023';
            end if;
        end loop;
        if pg_catalog.jsonb_typeof(v_reading -> 'quality_flags') is distinct from 'array' then
            raise exception 'reading.quality_flags must be an array' using errcode = '22023';
        end if;

        begin
            if (v_reading ->> 'poll_id')::uuid <> v_poll_id then
                raise exception 'reading.poll_id does not match p_poll.poll_id'
                    using errcode = '22023';
            end if;
            v_channel := (v_reading ->> 'channel')::integer;
            v_schema_version := (v_reading ->> 'schema_version')::integer;
            v_power_w := (v_reading ->> 'power_w')::double precision;
            v_voltage := (v_reading ->> 'voltage')::double precision;
            v_energy_total_wh := (v_reading ->> 'energy_total_wh')::double precision;
            v_created_at := (v_reading ->> 'created_at')::timestamptz;
            v_observed_at := (v_reading ->> 'observed_at')::timestamptz;
            v_reading_received_at := (v_reading ->> 'received_at')::timestamptz;
        exception
            when invalid_text_representation or numeric_value_out_of_range or datetime_field_overflow then
                raise exception 'a reading contains an invalid UUID, integer, number, or timestamp'
                    using errcode = '22023';
        end;

        v_sample_reason := v_reading ->> 'sample_reason';
        select coalesce(pg_catalog.array_agg(flag.value order by flag.ordinality), array[]::text[])
        into v_quality_flags
        from pg_catalog.jsonb_array_elements_text(v_reading -> 'quality_flags')
            with ordinality as flag(value, ordinality);

        for v_flag in
            select item.value
            from pg_catalog.jsonb_array_elements(v_reading -> 'quality_flags') as item(value)
        loop
            if pg_catalog.jsonb_typeof(v_flag) is distinct from 'string'
               or pg_catalog.btrim(v_flag #>> '{}') = ''
               or (v_flag #>> '{}') not in (
                   'channel_payload_invalid',
                   'power_missing', 'power_invalid', 'power_non_finite', 'power_out_of_range',
                   'voltage_missing', 'voltage_invalid', 'voltage_non_finite', 'voltage_out_of_range',
                   'energy_total_missing', 'energy_total_invalid', 'energy_total_non_finite',
                   'energy_total_out_of_range'
               ) then
                raise exception 'reading.quality_flags contains an unsupported value'
                    using errcode = '22023';
            end if;
        end loop;

        if pg_catalog.btrim(v_reading ->> 'site_id') <> v_site_id
           or pg_catalog.btrim(v_reading ->> 'device_id') <> v_device_id
           or pg_catalog.btrim(v_reading ->> 'collector_id') <> v_collector_id then
            raise exception 'reading lineage does not match p_poll' using errcode = '22023';
        end if;
        if v_schema_version <> v_sampling_policy_version then
            raise exception 'reading.schema_version does not match the poll policy version'
                using errcode = '22023';
        end if;
        if v_channel < 0 or v_channel = any (v_channels) then
            raise exception 'reading channels must be unique non-negative integers'
                using errcode = '22023';
        end if;
        v_channels := pg_catalog.array_append(v_channels, v_channel);
        if v_sample_reason not in ('first', 'active', 'turned_off', 'heartbeat', 'periodic', 'manual', 'recovered') then
            raise exception 'reading.sample_reason is unsupported' using errcode = '22023';
        end if;
        if (v_reading ->> 'created_at') !~ '(Z|[+-][0-9]{2}:[0-9]{2})$'
           or (v_reading ->> 'observed_at') !~ '(Z|[+-][0-9]{2}:[0-9]{2})$'
           or (v_reading ->> 'received_at') !~ '(Z|[+-][0-9]{2}:[0-9]{2})$' then
            raise exception 'reading timestamps must include a UTC offset'
                using errcode = '22023';
        end if;
        if v_created_at <> v_observed_at
           or v_observed_at > v_reading_received_at
           or v_reading_received_at <> v_received_at then
            raise exception 'reading timestamps are inconsistent with the poll'
                using errcode = '22023';
        end if;
        if v_power_w is not null and (v_power_w < 0 or v_power_w > 100000) then
            raise exception 'reading.power_w is out of range' using errcode = '22023';
        end if;
        if v_voltage is not null and (v_voltage < 0 or v_voltage > 500) then
            raise exception 'reading.voltage is out of range' using errcode = '22023';
        end if;
        if v_energy_total_wh is not null and v_energy_total_wh < 0 then
            raise exception 'reading.energy_total_wh is out of range' using errcode = '22023';
        end if;
        if v_power_w is null
           and not (v_quality_flags && array[
               'channel_payload_invalid', 'power_missing', 'power_invalid',
               'power_non_finite', 'power_out_of_range'
           ]::text[]) then
            raise exception 'NULL reading.power_w requires a matching quality flag'
                using errcode = '22023';
        end if;
        if v_voltage is null
           and not (v_quality_flags && array[
               'channel_payload_invalid', 'voltage_missing', 'voltage_invalid',
               'voltage_non_finite', 'voltage_out_of_range'
           ]::text[]) then
            raise exception 'NULL reading.voltage requires a matching quality flag'
                using errcode = '22023';
        end if;
        if v_energy_total_wh is null
           and not (v_quality_flags && array[
               'channel_payload_invalid', 'energy_total_missing', 'energy_total_invalid',
               'energy_total_non_finite', 'energy_total_out_of_range'
           ]::text[]) then
            raise exception 'NULL reading.energy_total_wh requires a matching quality flag'
                using errcode = '22023';
        end if;
    end loop;

    -- The advisory lock also serializes the first insert, for which no row is
    -- available to SELECT FOR UPDATE yet.
    perform pg_catalog.pg_advisory_xact_lock(
        pg_catalog.hashtextextended(v_poll_id::text, 0)
    );
    select poll.*
    into v_existing
    from public.telemetry_polls as poll
    where poll.poll_id = v_poll_id
    for update;
    v_had_existing := found;

    if v_had_existing and (
        v_existing.site_id <> v_site_id
        or v_existing.device_id <> v_device_id
        or v_existing.collector_id <> v_collector_id
        or v_existing.source <> v_source
        or v_existing.scheduled_at is distinct from v_scheduled_at
    ) then
        raise exception 'poll_id is already associated with different lineage'
            using errcode = '23505';
    end if;

    select pg_catalog.count(*)::integer
    into v_existing_reading_count
    from public.energy_readings as reading
    where reading.poll_id = v_poll_id;

    if v_outcome <> 'success' and v_had_existing and v_existing.outcome = 'success' then
        return pg_catalog.jsonb_build_object(
            'status', 'preserved_success',
            'poll_id', v_poll_id,
            'outcome', v_existing.outcome,
            'reading_count', v_existing_reading_count
        );
    end if;

    if not v_had_existing then
        insert into public.telemetry_polls (
            poll_id, site_id, device_id, collector_id, source,
            sampling_policy_version, scheduled_at, request_started_at,
            received_at, completed_at, outcome, error_code, error_message,
            latency_ms, http_status, poll_sequence, payload_hash, raw_payload
        ) values (
            v_poll_id, v_site_id, v_device_id, v_collector_id, v_source,
            v_sampling_policy_version, v_scheduled_at, v_request_started_at,
            v_received_at, v_completed_at, v_outcome, v_error_code, v_error_message,
            v_latency_ms, v_http_status, v_poll_sequence, v_payload_hash, v_raw_payload
        );
        v_status := case when v_outcome = 'success' then 'inserted' else 'recorded_error' end;
    elsif v_existing.outcome <> 'success' then
        update public.telemetry_polls as poll
        set sampling_policy_version = v_sampling_policy_version,
            request_started_at = v_request_started_at,
            received_at = v_received_at,
            completed_at = v_completed_at,
            outcome = v_outcome,
            error_code = v_error_code,
            error_message = v_error_message,
            latency_ms = v_latency_ms,
            http_status = v_http_status,
            poll_sequence = v_poll_sequence,
            payload_hash = v_payload_hash,
            raw_payload = v_raw_payload
        where poll.poll_id = v_poll_id;
        v_status := case when v_outcome = 'success' then 'promoted' else 'updated_error' end;
    else
        v_status := case
            when v_existing_reading_count < v_reading_count then 'repaired'
            else 'idempotent'
        end;
    end if;

    if v_outcome = 'success' then
        for v_reading in
            select item.value
            from pg_catalog.jsonb_array_elements(p_readings) as item(value)
        loop
            v_channel := (v_reading ->> 'channel')::integer;
            v_power_w := (v_reading ->> 'power_w')::double precision;
            v_voltage := (v_reading ->> 'voltage')::double precision;
            v_energy_total_wh := (v_reading ->> 'energy_total_wh')::double precision;
            v_created_at := (v_reading ->> 'created_at')::timestamptz;
            v_observed_at := (v_reading ->> 'observed_at')::timestamptz;
            v_reading_received_at := (v_reading ->> 'received_at')::timestamptz;
            v_sample_reason := v_reading ->> 'sample_reason';
            v_schema_version := (v_reading ->> 'schema_version')::integer;
            select coalesce(pg_catalog.array_agg(flag.value order by flag.ordinality), array[]::text[])
            into v_quality_flags
            from pg_catalog.jsonb_array_elements_text(v_reading -> 'quality_flags')
                with ordinality as flag(value, ordinality);

            insert into public.energy_readings (
                poll_id, site_id, device_id, channel, power_w, voltage,
                energy_total_wh, created_at, observed_at, received_at,
                collector_id, sample_reason, quality_flags, schema_version
            ) values (
                v_poll_id, v_site_id, v_device_id, v_channel, v_power_w, v_voltage,
                v_energy_total_wh, v_created_at, v_observed_at, v_reading_received_at,
                v_collector_id, v_sample_reason, v_quality_flags, v_schema_version
            )
            on conflict (poll_id, device_id, channel) do nothing;

            if not exists (
                select 1
                from public.energy_readings as stored
                where stored.poll_id = v_poll_id
                  and stored.site_id = v_site_id
                  and stored.device_id = v_device_id
                  and stored.channel = v_channel
                  and stored.power_w is not distinct from v_power_w
                  and stored.voltage is not distinct from v_voltage
                  and stored.energy_total_wh is not distinct from v_energy_total_wh
                  and stored.created_at = v_created_at
                  and stored.observed_at = v_observed_at
                  and stored.received_at = v_reading_received_at
                  and stored.collector_id = v_collector_id
                  and stored.sample_reason = v_sample_reason
                  and stored.quality_flags = v_quality_flags
                  and stored.schema_version = v_schema_version
            ) then
                raise exception 'poll retry conflicts with a previously committed channel reading'
                    using errcode = '23505';
            end if;
        end loop;

        select pg_catalog.count(*)::integer
        into v_final_reading_count
        from public.energy_readings as reading
        where reading.poll_id = v_poll_id;
        if v_final_reading_count <> v_reading_count then
            raise exception 'poll retry conflicts with the committed reading set'
                using errcode = '23505';
        end if;
    else
        v_final_reading_count := 0;
    end if;

    return pg_catalog.jsonb_build_object(
        'status', v_status,
        'poll_id', v_poll_id,
        'outcome', v_outcome,
        'reading_count', v_final_reading_count
    );
end
$function$;

revoke all on function public.ingest_telemetry_poll(jsonb, jsonb)
    from public, anon, authenticated;
grant execute on function public.ingest_telemetry_poll(jsonb, jsonb)
    to service_role;
comment on function public.ingest_telemetry_poll(jsonb, jsonb) is
    'Service-only atomic ingestion of one validated telemetry poll and its channel readings; deterministic retries preserve committed success.';

-- Canonical legacy RPC used by existing dashboard deployments. It intentionally
-- retains created_at as the bucket clock until every collector writes observed_at.
drop function if exists public.get_downsampled_readings(timestamptz, timestamptz, integer);
create function public.get_downsampled_readings(
    start_time timestamptz,
    end_time timestamptz,
    bucket_seconds integer
)
returns table (
    bucket_time timestamptz,
    channel integer,
    avg_power double precision
)
language plpgsql
stable
security invoker
set search_path = ''
as $function$
begin
    if start_time is null or end_time is null or start_time >= end_time then
        raise exception 'start_time must be earlier than end_time'
            using errcode = '22023';
    end if;
    if bucket_seconds is null or bucket_seconds < 1 or bucket_seconds > 86400 then
        raise exception 'bucket_seconds must be between 1 and 86400'
            using errcode = '22023';
    end if;

    return query
    select
        pg_catalog.to_timestamp(
            pg_catalog.floor(extract(epoch from er.created_at) / bucket_seconds::double precision)
            * bucket_seconds::double precision
        ) as bucket_time,
        er.channel::integer as channel,
        pg_catalog.avg(er.power_w)::double precision as avg_power
    from public.energy_readings as er
    where er.created_at >= start_time
      and er.created_at < end_time
    group by 1, er.channel
    order by 1, er.channel;
end
$function$;

-- Device-scoped equivalent for installations that have replaced or added a
-- meter. Filtering happens before grouping so two devices can never be averaged
-- into one apparent channel trace.
drop function if exists public.get_downsampled_readings_for_device(
    timestamptz,
    timestamptz,
    integer,
    text
);
drop function if exists public.get_downsampled_readings_for_device(
    timestamptz,
    timestamptz,
    integer,
    text,
    text
);
create function public.get_downsampled_readings_for_device(
    start_time timestamptz,
    end_time timestamptz,
    bucket_seconds integer,
    target_site_id text,
    target_device_id text
)
returns table (
    bucket_time timestamptz,
    channel integer,
    avg_power double precision
)
language plpgsql
stable
security invoker
set search_path = ''
as $function$
begin
    if start_time is null or end_time is null or start_time >= end_time then
        raise exception 'start_time must be earlier than end_time'
            using errcode = '22023';
    end if;
    if bucket_seconds is null or bucket_seconds < 1 or bucket_seconds > 86400 then
        raise exception 'bucket_seconds must be between 1 and 86400'
            using errcode = '22023';
    end if;
    if target_device_id is null or pg_catalog.btrim(target_device_id) = '' then
        raise exception 'target_device_id must not be empty'
            using errcode = '22023';
    end if;
    if target_site_id is null or pg_catalog.btrim(target_site_id) = '' then
        raise exception 'target_site_id must not be empty'
            using errcode = '22023';
    end if;

    return query
    select
        pg_catalog.to_timestamp(
            pg_catalog.floor(extract(epoch from er.created_at) / bucket_seconds::double precision)
            * bucket_seconds::double precision
        ) as bucket_time,
        er.channel::integer as channel,
        pg_catalog.avg(er.power_w)::double precision as avg_power
    from public.energy_readings as er
    where er.device_id = target_device_id
      and (er.site_id = target_site_id or er.site_id is null)
      and er.created_at >= start_time
      and er.created_at < end_time
    group by 1, er.channel
    order by 1, er.channel;
end
$function$;

-- Compact cumulative-counter series for energy calculations. Unlike the power
-- RPC, this returns the latest real counter observation in each bucket rather
-- than averaging counters or manufacturing interpolated samples.
drop function if exists public.get_energy_counter_series_for_device(
    timestamptz,
    timestamptz,
    integer,
    text,
    text
);
create function public.get_energy_counter_series_for_device(
    start_time timestamptz,
    end_time timestamptz,
    bucket_seconds integer,
    target_site_id text,
    target_device_id text
)
returns table (
    bucket_time timestamptz,
    device_id text,
    channel integer,
    energy_total_wh double precision,
    created_at timestamptz
)
language plpgsql
stable
security invoker
set search_path = ''
as $function$
begin
    if start_time is null or end_time is null or start_time >= end_time then
        raise exception 'start_time must be earlier than end_time'
            using errcode = '22023';
    end if;
    if bucket_seconds is null or bucket_seconds < 1 or bucket_seconds > 86400 then
        raise exception 'bucket_seconds must be between 1 and 86400'
            using errcode = '22023';
    end if;
    if target_site_id is null or pg_catalog.btrim(target_site_id) = '' then
        raise exception 'target_site_id must not be empty'
            using errcode = '22023';
    end if;
    if target_device_id is null or pg_catalog.btrim(target_device_id) = '' then
        raise exception 'target_device_id must not be empty'
            using errcode = '22023';
    end if;

    return query
    with bucketed as (
        select
            pg_catalog.to_timestamp(
                pg_catalog.floor(
                    extract(epoch from reading.created_at)
                    / bucket_seconds::double precision
                ) * bucket_seconds::double precision
            ) as sample_bucket,
            reading.device_id as sample_device_id,
            reading.channel::integer as sample_channel,
            reading.energy_total_wh::double precision as sample_energy_total_wh,
            reading.created_at as sample_created_at,
            reading.observed_at as sample_observed_at,
            reading.poll_id as sample_poll_id
        from public.energy_readings as reading
        where reading.device_id = target_device_id
          and (reading.site_id = target_site_id or reading.site_id is null)
          and reading.energy_total_wh is not null
          and reading.created_at >= start_time
          and reading.created_at < end_time
    )
    select distinct on (sample.sample_bucket, sample.sample_channel)
        sample.sample_bucket as bucket_time,
        sample.sample_device_id as device_id,
        sample.sample_channel as channel,
        sample.sample_energy_total_wh as energy_total_wh,
        sample.sample_created_at as created_at
    from bucketed as sample
    order by
        sample.sample_bucket,
        sample.sample_channel,
        sample.sample_created_at desc,
        sample.sample_observed_at desc nulls last,
        sample.sample_poll_id desc nulls last;
end
$function$;

revoke all on function public.get_downsampled_readings(timestamptz, timestamptz, integer)
    from public;
revoke all on function public.get_downsampled_readings_for_device(timestamptz, timestamptz, integer, text, text)
    from public;
revoke all on function public.get_energy_counter_series_for_device(timestamptz, timestamptz, integer, text, text)
    from public;

grant execute on function public.get_downsampled_readings(timestamptz, timestamptz, integer)
    to anon, authenticated, service_role;
grant execute on function public.get_downsampled_readings_for_device(timestamptz, timestamptz, integer, text, text)
    to anon, authenticated, service_role;
grant execute on function public.get_energy_counter_series_for_device(timestamptz, timestamptz, integer, text, text)
    to anon, authenticated, service_role;

comment on function public.get_downsampled_readings(timestamptz, timestamptz, integer) is
    'Read-only dashboard RPC. Buckets legacy telemetry from every device by channel.';
comment on function public.get_downsampled_readings_for_device(timestamptz, timestamptz, integer, text, text) is
    'Read-only dashboard RPC. Filters to one site and device before bucketing; includes same-device legacy rows whose site is NULL.';
comment on function public.get_energy_counter_series_for_device(timestamptz, timestamptz, integer, text, text) is
    'Read-only dashboard RPC. Returns the latest real non-NULL cumulative counter per site/device/channel bucket, preserving its source timestamp.';

commit;
